package: yform_field
version: '2.11.1'

author: 'alex+ Digitales Marketing: Alexander Walther, Paul Götz'
supportpage: https://github.com/alexplusde/yform_field

requires:
    redaxo: '^5.18.3'
    packages:
        yform: '>=4.1.1,<6'
        media_manager: '^2.16.0'
    php:
        version: ">=8.3,<9"
        extensions: [intl]


page:
    hidden: true
    title: 'Zusätzliche Felder'

pages:
    yform/yform_field_docs:
        title: 'Zusätzliche Felder'
        icon: rex-icon fa-puzzle-piece
        itemClass: pull-right
        perm: yform_field[]
