package: yform_field
version: '3.0.0-dev-2025-01-07'

author: 'alex+ Digitales Marketing: Alexander Walther, Paul Götz'
supportpage: https://github.com/alexplusde/yform_field

requires:
    redaxo: ^5.17
    packages:
        yform: '^4.1'
        media_manager: '^2.16.0'
    php:
        version: ">=8.2,<9"
        extensions: [intl]


page:
    hidden: true
    title: 'Zusätzliche Felder'

pages:
    yform/yform_field_docs:
        title: 'Zusätzliche Felder'
        icon: rex-icon fa-puzzle-piece
        itemClass: pull-right
        perm: yform_field[]
