package: yform_field
version: '2.4.0'

author: 'alex+ Digitales Marketing: Alexander Walther, Paul Götz'
supportpage: https://github.com/alexplusde/yform_field

requires:
    redaxo: ^5.15
    yform: '^4.1'
    media_manager: '2.12.1'
    php:
        version: ">=8.1,<9"
        extensions: [intl]


page:
    hidden: true

pages:
    yform/yform_field_docs:
        title: 'Zusätzliche Felder'
        icon: rex-icon fa-puzzle-piece
        itemclass: pull-right
        perm: yform_field[]
